### ISSUE TITLE
无法启动 

### ISSUE THREAD

**Issue by lijiaxing127** [wechaty/php-wechaty#12]
start Wechaty
Array
(
    [0] => start() rejection:
    [1] => GuzzleHttp\Exception\ClientException Object
        (
            [request:GuzzleHttp\Exception\RequestException:private] => GuzzleHttp\Psr7\Request Object
                (
                    [method:GuzzleHttp\Psr7\Request:private] => GET
                    [requestTarget:GuzzleHttp\Psr7\Request:private] => 
                    [uri:GuzzleHttp\Psr7\Request:private] => GuzzleHttp\Psr7\Uri Object
                        (
                            [scheme:GuzzleHttp\Psr7\Uri:private] => https
                            [userInfo:GuzzleHttp\Psr7\Uri:private] => 
                            [host:GuzzleHttp\Psr7\Uri:private] => api.chatie.io
                            [port:GuzzleHttp\Psr7\Uri:private] => 
                            [path:GuzzleHttp\Psr7\Uri:private] => /v0/hosties/puppet_paimon_0eff4064-b5de-4866-912c-aa2df3fc1793
                            [query:GuzzleHttp\Psr7\Uri:private] => 
                            [fragment:GuzzleHttp\Psr7\Uri:private] => 
                            [composedComponents:GuzzleHttp\Psr7\Uri:private] => https://api.chatie.io/v0/hosties/puppet_paimon_0eff4064-b5de-4866-912c-aa2df3fc1793
                        )

                    [headers:GuzzleHttp\Psr7\Request:private] => Array
                        (
                            [User-Agent] => Array
                                (
                                    [0] => GuzzleHttp/7
                                )

                            [Host] => Array
                                (
                                    [0] => api.chatie.io
                                )

                        )

                    [headerNames:GuzzleHttp\Psr7\Request:private] => Array
                        (
                            [user-agent] => User-Agent
                            [host] => Host
                        )

                    [protocol:GuzzleHttp\Psr7\Request:private] => 1.1
                    [stream:GuzzleHttp\Psr7\Request:private] => GuzzleHttp\Psr7\Stream Object
                        (
                            [stream:GuzzleHttp\Psr7\Stream:private] => Resource id #57
                            [size:GuzzleHttp\Psr7\Stream:private] => 0
                            [seekable:GuzzleHttp\Psr7\Stream:private] => 1
                            [readable:GuzzleHttp\Psr7\Stream:private] => 1
                            [writable:GuzzleHttp\Psr7\Stream:private] => 1
                            [uri:GuzzleHttp\Psr7\Stream:private] => php://temp
                            [customMetadata:GuzzleHttp\Psr7\Stream:private] => Array
                                (
                                )

                        )

                )

            [response:GuzzleHttp\Exception\RequestException:private] => GuzzleHttp\Psr7\Response Object
                (
                    [reasonPhrase:GuzzleHttp\Psr7\Response:private] => Not Found
                    [statusCode:GuzzleHttp\Psr7\Response:private] => 404
                    [headers:GuzzleHttp\Psr7\Response:private] => Array
                        (
                            [Date] => Array
                                (
                                    [0] => Wed, 13 Oct 2021 07:25:54 GMT
                                )

                            [Content-Type] => Array
                                (
                                    [0] => application/json; charset=utf-8
                                )

                            [Content-Length] => Array
                                (
                                    [0] => 42
                                )

                            [Connection] => Array
                                (
                                    [0] => keep-alive
                                )

                            [x-powered-by] => Array
                                (
                                    [0] => Express
                                )

                            [etag] => Array
                                (
                                    [0] => W/"2a-SuVhOFyPl8dQs2TQ8aOIDrRe/LQ"
                                )

                            [via] => Array
                                (
                                    [0] => 1.1 vegur
                                )

                            [CF-Cache-Status] => Array
                                (
                                    [0] => DYNAMIC
                                )

                            [Expect-CT] => Array
                                (
                                    [0] => max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
                                )

                            [Report-To] => Array
                                (
                                    [0] => {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=D9sl8rIGNuXKTdRFpWMJGQuEyqrTl5%2BbEKKp3sjXwowECJZn%2FZS%2B36Al7WsVY901LArlCKA5WHdIiYvSu2OAgsqgRjoZoOFQGbt9JPVr9m%2FzCUUeEo2WCmvUHZM37E3C"}],"group":"cf-nel","max_age":604800}
                                )

                            [NEL] => Array
                                (
                                    [0] => {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
                                )

                            [Server] => Array
                                (
                                    [0] => cloudflare
                                )

                            [CF-RAY] => Array
                                (
                                    [0] => 69d6d62f78cf3684-LAX
                                )

                            [alt-svc] => Array
                                (
                                    [0] => h3=":443"; ma=86400, h3-29=":443"; ma=86400, h3-28=":443"; ma=86400, h3-27=":443"; ma=86400
                                )

                        )

                    [headerNames:GuzzleHttp\Psr7\Response:private] => Array
                        (
                            [date] => Date
                            [content-type] => Content-Type
                            [content-length] => Content-Length
                            [connection] => Connection
                            [x-powered-by] => x-powered-by
                            [etag] => etag
                            [via] => via
                            [cf-cache-status] => CF-Cache-Status
                            [expect-ct] => Expect-CT
                            [report-to] => Report-To
                            [nel] => NEL
                            [server] => Server
                            [cf-ray] => CF-RAY
                            [alt-svc] => alt-svc
                        )

                    [protocol:GuzzleHttp\Psr7\Response:private] => 1.1
                    [stream:GuzzleHttp\Psr7\Response:private] => GuzzleHttp\Psr7\Stream Object
                        (
                            [stream:GuzzleHttp\Psr7\Stream:private] => Resource id #64
                            [size:GuzzleHttp\Psr7\Stream:private] => 42
                            [seekable:GuzzleHttp\Psr7\Stream:private] => 1
                            [readable:GuzzleHttp\Psr7\Stream:private] => 1
                            [writable:GuzzleHttp\Psr7\Stream:private] => 1
                            [uri:GuzzleHttp\Psr7\Stream:private] => php://temp
                            [customMetadata:GuzzleHttp\Psr7\Stream:private] => Array
                                (
                                )

                        )

                )

            [handlerContext:GuzzleHttp\Exception\RequestException:private] => Array
                (
                )

            [message:protected] => Client error: `GET https://api.chatie.io/v0/hosties/puppet_paimon_0eff4064-b5de-4866-912c-aa2df3fc1793` resulted in a `404 Not Found` response:
{"host":"0.0.0.0","ip":"0.0.0.0","port":0}

            [string:Exception:private] => 
            [code:protected] => 404
            [file:protected] => /root/php-wechaty-master/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php
            [line:protected] => 113
            [trace:Exception:private] => Array
                (
                    [0] => Array
                        (
                            [file] => /root/php-wechaty-master/vendor/guzzlehttp/guzzle/src/Middleware.php
                            [line] => 69
                            [function] => create
                            [class] => GuzzleHttp\Exception\RequestException
                            [type] => ::
                        )

                    [1] => Array
                        (
                            [file] => /root/php-wechaty-master/vendor/guzzlehttp/promises/src/Promise.php
                            [line] => 204
                            [function] => GuzzleHttp\{closure}
                            [class] => GuzzleHttp\Middleware
                            [type] => ::
                        )

                    [2] => Array
                        (
                            [file] => /root/php-wechaty-master/vendor/guzzlehttp/promises/src/Promise.php
                            [line] => 153
                            [function] => callHandler
                            [class] => GuzzleHttp\Promise\Promise
                            [type] => ::
                        )

                    [3] => Array
                        (
                            [file] => /root/php-wechaty-master/vendor/guzzlehttp/promises/src/TaskQueue.php
                            [line] => 48
                            [function] => GuzzleHttp\Promise\{closure}
                            [class] => GuzzleHttp\Promise\Promise
                            [type] => ::
                        )

                    [4] => Array
                        (
                            [file] => /root/php-wechaty-master/vendor/guzzlehttp/promises/src/Promise.php
                            [line] => 248
                            [function] => run
                            [class] => GuzzleHttp\Promise\TaskQueue
                            [type] => ->
                        )

                    [5] => Array
                        (
                            [file] => /root/php-wechaty-master/vendor/guzzlehttp/promises/src/Promise.php
                            [line] => 224
                            [function] => invokeWaitFn
                            [class] => GuzzleHttp\Promise\Promise
                            [type] => ->
                        )

                    [6] => Array
                        (
                            [file] => /root/php-wechaty-master/vendor/guzzlehttp/promises/src/Promise.php
                            [line] => 269
                            [function] => waitIfPending
                            [class] => GuzzleHttp\Promise\Promise
                            [type] => ->
                        )

                    [7] => Array
                        (
                            [file] => /root/php-wechaty-master/vendor/guzzlehttp/promises/src/Promise.php
                            [line] => 226
                            [function] => invokeWaitList
                            [class] => GuzzleHttp\Promise\Promise
                            [type] => ->
                        )

                    [8] => Array
                        (
                            [file] => /root/php-wechaty-master/vendor/guzzlehttp/promises/src/Promise.php
                            [line] => 62
                            [function] => waitIfPending
                            [class] => GuzzleHttp\Promise\Promise
                            [type] => ->
                        )

                    [9] => Array
                        (
                            [file] => /root/php-wechaty-master/vendor/guzzlehttp/guzzle/src/Client.php
                            [line] => 187
                            [function] => wait
                            [class] => GuzzleHttp\Promise\Promise
                            [type] => ->
                        )

                    [10] => Array
                        (
                            [file] => /root/php-wechaty-master/wechaty-puppet-hostie/IO/Github/Wechaty/PuppetHostie/PuppetHostie.php
                            [line] => 805
                            [function] => request
                            [class] => GuzzleHttp\Client
                            [type] => ->
                        )

                    [11] => Array
                        (
                            [file] => /root/php-wechaty-master/wechaty-puppet-hostie/IO/Github/Wechaty/PuppetHostie/PuppetHostie.php
                            [line] => 759
                            [function] => _discoverHostieIp
                            [class] => IO\Github\Wechaty\PuppetHostie\PuppetHostie
                            [type] => ->
                        )

                    [12] => Array
                        (
                            [file] => /root/php-wechaty-master/wechaty-puppet-hostie/IO/Github/Wechaty/PuppetHostie/PuppetHostie.php
                            [line] => 59
                            [function] => _startGrpcClient
                            [class] => IO\Github\Wechaty\PuppetHostie\PuppetHostie
                            [type] => ->
                        )

                    [13] => Array
                        (
                            [file] => /root/php-wechaty-master/wechaty/IO/Github/Wechaty/Wechaty.php
                            [line] => 137
                            [function] => start
                            [class] => IO\Github\Wechaty\PuppetHostie\PuppetHostie
                            [type] => ->
                        )

                    [14] => Array
                        (
                            [file] => /root/php-wechaty-master/examples/ding-dong-bot.php
                            [line] => 77
                            [function] => start
                            [class] => IO\Github\Wechaty\Wechaty
                            [type] => ->
                        )

                )

            [previous:Exception:private] => 
        )

)

**Comment by lijiaxing127** [comment]
> 请参阅https://wechaty.js.org/docs/puppet-services/diy/

echo HTTP/$(curl -s -o /dev/null -w '%{http_code}' https://api.chatie.io/v0/hosties/puppet_padlocal_77661b0800d445e5bdc4f61e9b256a32)
HTTP/200
![image](https://user-images.githubusercontent.com/75360884/137107481-ae824333-8c5b-416c-887a-0eaf49b85ae0.png)

**Comment by zhangchunsheng** [comment]
see https://github.com/wechaty/docker-wechaty-getting-started
