### ISSUE TITLE
Environment variable name update: WECHATY_PUPPET_SERVICE_ENDPOINT

### ISSUE THREAD

**Issue by huan** [wechaty/php-wechaty#14]
We have updated the `HOSTIE` name to `SERVICE`, and so does in the code class/variable names. (i.e. `PuppetHostie` -> `PuppetService`)

```diff
- WECHATY_PUPPET_HOSTIE_ENDPOINT
+ WECHATY_PUPPET_SERVICE_ENDPOINT
```

```diff
- PuppetHostie
- PuppetService
```

```diff
- wechaty-puppet-hostie
+ wechaty-puppet-service
```

**Comment by zhangchunsheng** [comment]
What about the url "https://api.chatie.io/v0/hosties"?

I think this url need to be changed.

**Comment by huan** [comment]
The server API will not be changed because it will cause unnecessary breaking changes.

In TypeScript, we have a [Wechaty gRPC Resolver](https://github.com/wechaty/token#grpc-resolver-usage) for encapsulating this logic, please refer to the source code and see if it can inspire the PHP.

https://github.com/wechaty/token/blob/main/src/wechaty-token.ts
