### ISSUE TITLE
Class 'Grpc\ChannelCredentials' not found

### ISSUE THREAD

**Issue by BigXia** [wechaty/php-wechaty#4]
PHP 7.4.13 
MacOS 10.15.6
报错not found，请问怎么解决？

![image](https://user-images.githubusercontent.com/22040380/103195718-c6049380-491d-11eb-9e6c-b15bc1e322b3.png)

**Comment by huan** [comment]
Have you tried our PHP Wechaty Getting Started repo at <https://github.com/wechaty/php-wechaty-getting-started> ?

I believe that repo should be a good entry to start.

**Comment by BigXia** [comment]
> Have you tried our PHP Wechaty Getting Started repo at https://github.com/wechaty/php-wechaty-getting-started ?
> 
> I believe that repo should be a good entry to start.

![image](https://user-images.githubusercontent.com/22040380/103516914-41c98780-4eac-11eb-9d26-bd3302fb3273.png)

Can not work normally,too.

**Comment by zhangchunsheng** [comment]
You should install php extension.

You can use yum on CentOS.
```
sudo yum install php-pecl-grpc
sudo yum install php-pecl-protobuf
sudo yum install php-pecl-yac
sudo yum install php-xml
```

**Comment by zhangchunsheng** [comment]
see https://github.com/wechaty/docker-wechaty-getting-started
